services:
  tbs-b-db:
    image: mysql:8.4
    container_name: tbs-b-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${TBS_DB_ROOT_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - tbs_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - backend

  tbs-b-redis:
    image: redis:7.2
    container_name:  tbs-b-redis
    ports:
      - "6380:6379"
    command: >
      redis-server 
      --maxmemory 100mb 
      --maxmemory-policy allkeys-lru
      --bind 0.0.0.0
    restart: unless-stopped
    networks:
      - backend

  tbs-b-auth-service:
    build:
      context: .
      dockerfile: Auth/Dockerfile
    container_name:  tbs-b-auth-service
    depends_on:
      - tbs-b-db
      - tbs-b-redis
    ports:
      - "5030:5030"
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5030
      - ConnectionStrings__DefaultConnection=${TBS_DB_AUTH_CONNECTION_STRING}
      - ConnectionStrings__Redis=${TBS_DB_REDIS}

volumes:
  tbs_data:

networks:
  backend:
    driver: bridge



