services:
  tbs_b_account_db:
    image: mysql:8.4
    container_name: tbs-account-db
    restart: always
    environment:
      MYSQL_DATABASE: account_db
      MYSQL_USER: ${TBS_DB_ACCOUNT_USER}
      MYSQL_PASSWORD: ${TBS_DB_ACCOUNT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${TBS_DB_ACCOUNT_ROOT_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - tbs_account_data:/var/lib/mysql
    networks:
      - backend

  redis_account:
    image: redis:7.2
    container_name: redis-account
    ports:
      - "6380:6379"
    command: >
      redis-server 
      --maxmemory 100mb 
      --maxmemory-policy allkeys-lru
    restart: unless-stopped

volumes:
  tbs_account_data:

networks:
  backend:
    driver: bridge



